name: 每日数据爬取

on:
  schedule:
    # 每天凌晨2点运行 (UTC时间，对应北京时间10点)
    - cron: '0 2 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape-and-store:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的历史记录，避免git冲突
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pillow
          
      - name: 创建必要的目录
        run: |
          mkdir -p data logs icons
          
      - name: 运行爬虫
        run: |
          python src/main.py run all
          
      - name: 归档旧数据
        run: |
          python src/main.py archive all --weeks 12
          
      - name: 配置Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: 提交并推送更改
        run: |
          git add data/ logs/ icons/
          # 检查是否有更改需要提交
          if git diff --staged --quiet; then
            echo "没有更改需要提交"
          else
            # 获取当前日期用于提交信息
            DATE=$(date +'%Y-%m-%d')
            git commit -m "更新爬取数据: $DATE"
            git push
          fi
          
      - name: 输出爬取结果摘要
        run: |
          echo "爬取完成，数据源列表："
          python src/main.py list-sources
          
          echo "可用周数据："
          for source in $(python src/main.py list-sources | grep "^- " | cut -d " " -f 2 | cut -d "(" -f 1); do
            echo "* $source:"
            python src/main.py list-weeks $source | head -n 3 | sed 's/^/  /'
          done